#
# This file is part of BDC-ODC
# Copyright 2020 INPE.
#
# bdc-odc is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import sphinx_rtd_theme


# -- Project information -----------------------------------------------------

project = 'BDC-ODC Documentation'
copyright = '2020, INPE.'
author = 'Brazil Data Cube Team'

# The full version, including alpha/beta/rc tags
release = '2020'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx_copybutton',
    'sphinx.ext.todo',
    'sphinx_rtd_theme',
    'sphinx_tabs.tabs',

]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en_US'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
]


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

html_theme_options = {
    'canonical_url': 'https://brazil-data-cube.github.io/',
    'analytics_id': 'XXXXXXXXXX',
    'logo_only': True,
    'display_version': True,
    'prev_next_buttons_location': 'both',
    'style_external_links': True,
    #'vcs_pageview_mode': 'edit',
    #'github_url': 'https://github.com/geosec/docs-geo-knowledge-hub',
    'style_nav_header_background': '#F0F8FF',
    'collapse_navigation': True,
    'sticky_navigation': False,
    'navigation_depth': 3,
    'includehidden': True,
    'titles_only': False
}

#html_theme_path = ''

#html_style = ''

html_title = 'Brazil Data Cube'

html_context = {
    'display_github': True,
    'github_user': 'brazil-data-cube',
    'github_repo': 'bdc-odc',
    'last_updated': False,
    #'commit': False,
}

html_show_sourcelink = False

html_logo = './img/odc/logo-odc-bdc.png'

html_favicon = './img/favicon.ico'

html_static_path = ['_static']

html_css_files = [
    #'bdc-odc.css',
]

html_last_updated_fmt = '%b %d, %Y'

html_show_sphinx = False

# html_search_language = 'pt'

numfig = True

numfig_format = {
    'figure': 'Figure %s -',
    'table': 'Table %s -',
    'code-block': 'Code snippet %s -',
#    'section': 'Section %s.'
}

master_doc = 'index'
